version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-book-room"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mc54cyjp7moo"
s3_prefix = "aws-book-room"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
